# Generated by Django 2.0.5 on 2020-03-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0003_logs_sreenshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sreenshots',
            name='screenshots',
            field=models.ImageField(upload_to='screenshots'),
        ),
    ]
