# Generated by Django 2.0.5 on 2020-03-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0005_auto_20200302_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sreenshots',
            old_name='screenshots',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='host',
            name='team',
        ),
        migrations.AddField(
            model_name='sreenshots',
            name='description',
            field=models.CharField(default=None, max_length=100000),
        ),
    ]
