# Generated by Django 2.0.5 on 2020-03-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0007_auto_20200305_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100000000),
        ),
        migrations.AlterField(
            model_name='sreenshots',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=100000000),
        ),
    ]
