# Generated by Django 2.0.5 on 2020-03-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0010_auto_20200314_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('a', 'Red'), ('b', 'Blue')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='logs',
            name='team',
            field=models.ManyToManyField(to='hosts.Team'),
        ),
        migrations.AddField(
            model_name='sreenshots',
            name='team',
            field=models.ManyToManyField(to='hosts.Team'),
        ),
    ]
