# Generated by Django 2.0.5 on 2020-03-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0011_auto_20200314_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue')], max_length=1),
        ),
    ]
