# Generated by Django 2.0.5 on 2020-03-15 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0013_auto_20200314_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='categories',
        ),
        migrations.AddField(
            model_name='logs',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Category'),
        ),
        migrations.RemoveField(
            model_name='logs',
            name='ip_source',
        ),
        migrations.AddField(
            model_name='logs',
            name='ip_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Source'),
        ),
        migrations.RemoveField(
            model_name='logs',
            name='team',
        ),
        migrations.AddField(
            model_name='logs',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Team'),
        ),
        migrations.RemoveField(
            model_name='sreenshots',
            name='categories',
        ),
        migrations.AddField(
            model_name='sreenshots',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Category'),
        ),
        migrations.RemoveField(
            model_name='sreenshots',
            name='ip_source',
        ),
        migrations.AddField(
            model_name='sreenshots',
            name='ip_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Source'),
        ),
        migrations.RemoveField(
            model_name='sreenshots',
            name='team',
        ),
        migrations.AddField(
            model_name='sreenshots',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Team'),
        ),
    ]
