# Generated by Django 2.0.5 on 2020-03-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0014_auto_20200315_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
