# Generated by Django 2.0.5 on 2020-03-22 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0015_auto_20200320_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='ip_source',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='team',
        ),
        migrations.RemoveField(
            model_name='sreenshots',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='sreenshots',
            name='ip_source',
        ),
        migrations.RemoveField(
            model_name='sreenshots',
            name='team',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
