# Generated by Django 2.0.5 on 2020-03-22 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0017_category_source_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Category'),
        ),
        migrations.AddField(
            model_name='logs',
            name='ip_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Source'),
        ),
        migrations.AddField(
            model_name='logs',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Team'),
        ),
        migrations.AddField(
            model_name='sreenshots',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Category'),
        ),
        migrations.AddField(
            model_name='sreenshots',
            name='ip_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Source'),
        ),
        migrations.AddField(
            model_name='sreenshots',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosts.Team'),
        ),
    ]
