# Generated by Django 2.0.5 on 2020-03-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0021_auto_20200322_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('img', models.ImageField(upload_to='static/img')),
                ('description', models.CharField(blank=True, default=None, max_length=100000000)),
            ],
        ),
    ]
